services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      PG_HOST: db
      PG_USER: postgres
      PG_DATABASE: postgres
      PG_PASSWORD: postgres
      DOMAIN: http://localhost:8080
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.pg
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
