// Code generated by lesiw.io/plain. DO NOT EDIT.

package main

import (
	"embed"

	"lesiw.io/plain"
)

//go:embed sql/migrations/*
var migrations embed.FS

func migrate() error {
	return plain.Migrate(migrations)
}
